### ISSUE TITLE
Enable "fly" and "fast" modes for all joined players by default

### ISSUE THREAD

**Issue by metacoma** [9mine/9mine#43]
https://wiki.minetest.net/Privileges

**Comment by dievri** [comment]
Privileges enabled on client side.

On server side can be changed player physics to achieve result similar to privs with  `set_physics_override(override_table)`

https://github.com/minetest/minetest/blob/3176daee79a8e91bd16fc275704f49fe1648db32/doc/lua_api.txt#L6360

**Comment by dievri** [comment]
In servers source code, 'fly' and 'fast' are set by default to false
https://github.com/minetest/minetest/blob/2f6393f49d5ebf21abfaa7bff876b8c0cf4ca191/src/defaultsettings.cpp#L47
https://github.com/minetest/minetest/blob/2f6393f49d5ebf21abfaa7bff876b8c0cf4ca191/src/defaultsettings.cpp#L49
