### ISSUE TITLE
Global Registry

### ISSUE THREAD

**Issue by dievri** [9mine/9mine#56]
Providing the 9p global registry of public 9p servers and registry list

**Comment by metacoma** [comment]
```

tcp!registry.9gridchan.org!6675 (KUDOS TO mycroftiv 9ridchan registry)
tcp!registry.9gridchan.org!7675 public 9gridchan registry
tcp!dum.a-b.xyz!905 - /lib/rfc as a Service (thanks to kvik)
tcp!docs.a-b.xyz!909 -- docs.a-b.xyz as a Service (thanks to kvik)
tcp!oat.nine.sirjofri.de!564 (thanks to sirjofri)
tcp!ftrv.se!564 (thanks to sigrid)
tcp!9p.io!564 (9p.io)
tcp!postnix.pw!9fs The Sources mirror (thanks to henesy)
tcp!postnix.pw!626 Audio manuals (thank to henesy)
tcp!postnix.pw!465 The web mirrors of misc (9) projects (thanks to henesy)

tcp!contrib.9front.org!564
tcp!9front.org!7734

tcp!coeus.antares-labs.eu!65009 gridbiblia

tcp!kamalatta.ddnss.de!999 guestbook
tcp!kamalatta.ddnss.de!9997 hubfs chat
```

**Comment by metacoma** [comment]
> ```
> 
> tcp!registry.9gridchan.org!6675 (KUDOS TO mycroftiv 9ridchan registry)
> tcp!registry.9gridchan.org!7675 public 9gridchan registry
> tcp!dum.a-b.xyz!905 - /lib/rfc as a Service (thanks to kvik)
> tcp!docs.a-b.xyz!909 -- docs.a-b.xyz as a Service (thanks to kvik)
> tcp!oat.nine.sirjofri.de!564 (thanks to sirjofri)
> tcp!ftrv.se!564 (thanks to sigrid)
> tcp!9p.io!564 (9p.io)
> tcp!postnix.pw!9fs The Sources mirror (thanks to henesy)
> tcp!postnix.pw!626 Audio manuals (thank to henesy)
> tcp!postnix.pw!465 The web mirrors of misc (9) projects (thanks to henesy)
> 
> tcp!contrib.9front.org!564
> tcp!9front.org!7734
> 
> tcp!coeus.antares-labs.eu!65009 gridbiblia
> 
> tcp!kamalatta.ddnss.de!999 guestbook
> tcp!kamalatta.ddnss.de!9997 hubfs chat
> ```

the "meta-registry" has address `tcp!registry.dev.metacoma.io!30099`
