### ISSUE TITLE
Add 9front/inferno man pages in formspec format

### ISSUE THREAD

**Issue by metacoma** [9mine/9mine#78]

**Comment by dievri** [comment]
Lines are trimmed with hypertext
<pre>
`<global background=yellow color=black><big>1.\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ hellothere\n \\ \\ \\hithere</big>
</pre>
![Screenshot_2020-12-21_11-25-29](https://user-images.githubusercontent.com/22656939/102769121-e1562880-438a-11eb-811c-7151ba529580.png)

<pre>
<global background=yellow color=black><big>\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ hellothere\n \\ \\ \\hithere</big></pre>
![Screenshot_2020-12-21_11-27-01](https://user-images.githubusercontent.com/22656939/102769134-e6b37300-438a-11eb-9510-d39b28944245.png)
